"""create tables

Revision ID: c8b148fd23c0
Revises: 
Create Date: 2026-07-09 10:40:07.377851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8b148fd23c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('equipment_needed', sa.Boolean(), nullable=False),
    sa.CheckConstraint("name != ''", name=op.f('ck_exercises_name_not_empty')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercises')),
    sa.UniqueConstraint('name', name=op.f('uq_exercises_name'))
    )
    op.create_table('workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('duration_minutes > 0', name=op.f('ck_workouts_duration_minutes_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workouts'))
    )
    op.create_table('workout_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.CheckConstraint('duration_seconds > 0', name=op.f('ck_workout_exercises_duration_seconds_positive')),
    sa.CheckConstraint('reps > 0', name=op.f('ck_workout_exercises_reps_positive')),
    sa.CheckConstraint('sets > 0', name=op.f('ck_workout_exercises_sets_positive')),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_workout_exercises_exercise_id_exercises')),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], name=op.f('fk_workout_exercises_workout_id_workouts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workout_exercises')),
    sa.UniqueConstraint('workout_id', 'exercise_id', name='uq_workout_exercise')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_exercises')
    op.drop_table('workouts')
    op.drop_table('exercises')
    # ### end Alembic commands ###
